### ISSUE TITLE
csv parsing fails when rising searches between 1000% and 5000%

### ISSUE THREAD

**Issue by bdewilde** [dreyco676/pytrends#12]
Unbelievably, it looks like Google Trends outputs comma-separated files that separate numerical values in the thousands with, yes, a comma:

```
Rising searches for Egg
dragon city,Breakout
яйцо,+1,650%
trung,+1,600%
яйца,+800%
...
```

This is malformed CSV that gets wrongly parsed in, say, MS Excel, and it throws an exception in `parse_data()`. I'll work on making the parsing code more robust, particularly to this issue. Hope it doesn't get too complex.

**Comment by dreyco676** [comment]
Hmm might be able to write a regex to quote it or convert it.

**Comment by bdewilde** [comment]
Yup, regex was the easiest way to do it. I added a function to clean subtables (although, I suppose, it could possibly be applied to all tables at once). It's currently in the refactor branch — if that's inconvenient, I could just edit it in another branch or master directly. See commit 84af56c76de7a7b5c4f9f549aac1a71a8dd5d8e2 .

**Comment by dreyco676** [comment]
If you think your refactor branch might take a few days I'd add it separately. I'd prefer to keep bus closed as to not scare anyone off. :-P
