### ISSUE TITLE
`hl` parameter doesn't limit results

### ISSUE THREAD

**Issue by bdewilde** [dreyco676/pytrends#16]
Hey, as far as I can tell, the `hl` parameter works across most Google services to set the language of the web interface, but it _doesn't_ filter results (for trends, searches, etc.) by that language. The repo's readme claims otherwise. Could you double-check, @dreyco676?

**Comment by dreyco676** [comment]
Thanks corrected. It only changes the language of the result headers.

**Comment by bdewilde** [comment]
Aha, I see that now. I made a couple changes so the parsing code is robust to unicode (non-ascii) characters, but I'll have to make a couple more. Thanks for clarifying!
