### ISSUE TITLE
Date Parameter Change

### ISSUE THREAD

**Issue by dandxy89** [dreyco676/pytrends#19]
MINOR

From testing the date parameters changed - it appears to have only affected the Daily and Hourly patterns:

Daily: date="today 12-m"
Hourly: date="now 1-H"

**Comment by dreyco676** [comment]
If I understand correctly you are saying there is now a space?

**Comment by dreyco676** [comment]
fixed

**Comment by dandxy89** [comment]
Yes - apologies should have been clearer.
