### ISSUE TITLE
packaging and pypi?

### ISSUE THREAD

**Issue by bdewilde** [dreyco676/pytrends#5]
Is there any interest in restructuring this project into a module distribution and adding a setup.py for installation? Maybe also building a source distribution and uploading it to PyPi? I've never done this before but I'm happy to take a first pass and send a pull request.

**Comment by dreyco676** [comment]
I would love that. I would also love to learn how to do that.

**Comment by bdewilde** [comment]
As far as I can tell, the [Python Packaging User Guide](https://packaging.python.org/en/latest/index.html) is the official source of _up-to-date_ information. I've created a `setup` branch with a `setup.py` and a typical directory structure. Pull Request on the way...

**Comment by dreyco676** [comment]
done, its on pypi now.
